// example export { default as example } from './example.js'
export { default as products } from './products.js'
export { default as login } from './login.js'
export { default as register } from './register.js'
export { default as error } from './error.js'
